<?php
// config/locations.php
// Centralized provinces and showroom mappings used by checkout/order flow.
return [
    'provinces' => [
        'Hà Nội',
        'Hồ Chí Minh',
        'Đà Nẵng',
        'Hải Phòng',
        'Cần Thơ',
        'An Giang',
        'Bà Rịa - Vũng Tàu',
        'Bắc Giang',
        'Bắc Ninh',
        'Bình Định',
        'Bình Dương',
        'Bình Phước',
        'Bình Thuận',
        'Cà Mau',
        'Đắk Lắk',
        'Đồng Nai',
        'Đồng Tháp',
        'Gia Lai',
        'Hà Nam',
        'Hà Tĩnh',
        'Hải Dương',
        'Hậu Giang',
        'Khánh Hòa',
        'Kiên Giang',
        'Lâm Đồng',
        'Long An',
        'Nam Định',
        'Nghệ An',
        'Ninh Bình',
        'Phú Thọ',
        'Quảng Bình',
        'Quảng Nam',
        'Quảng Ninh',
        'Quảng Trị',
        'Sóc Trăng',
        'Thanh Hóa',
        'Thừa Thiên Huế',
        'Tiền Giang',
        'Vĩnh Long',
        'Vĩnh Phúc',
    ],

    'showrooms' => [
        'Hà Nội' => ['VinFast Hà Nội - Tố Hữu', 'VinFast Hà Nội - Phạm Hùng', 'VinFast Hà Nội - Phú Thượng'],
        'Hồ Chí Minh' => ['VinFast HCM - Quận 7', 'VinFast HCM - Bình Thạnh', 'VinFast HCM - Thủ Đức'],
        'Đà Nẵng' => ['VinFast Đà Nẵng - Nguyễn Văn Linh'],
        'Hải Phòng' => ['VinFast Hải Phòng - Lê Hồng Phong'],
        'Cần Thơ' => ['VinFast Cần Thơ - Nguyễn Văn Cừ'],
        'An Giang' => ['VinFast An Giang - Châu Đốc'],
        'Bà Rịa - Vũng Tàu' => ['VinFast Vũng Tàu - Lê Hồng Phong'],
        'Bắc Giang' => ['VinFast Bắc Giang - Nguyễn Văn Cừ'],
        'Bắc Ninh' => ['VinFast Bắc Ninh - Lý Thái Tổ'],
        'Bình Định' => ['VinFast Bình Định - Nguyễn Thái Học'],
        'Bình Dương' => ['VinFast Bình Dương - Thủ Dầu Một'],
        'Bình Phước' => ['VinFast Bình Phước - Đồng Xoài'],
        'Bình Thuận' => ['VinFast Bình Thuận - Phan Thiết'],
        'Cà Mau' => ['VinFast Cà Mau - Nguyễn Hữu Thọ'],
        'Đắk Lắk' => ['VinFast Đắk Lắk - Buôn Ma Thuột'],
        'Đồng Nai' => ['VinFast Đồng Nai - Biên Hòa'],
        'Đồng Tháp' => ['VinFast Đồng Tháp - Cao Lãnh'],
        'Gia Lai' => ['VinFast Gia Lai - Pleiku'],
        'Hà Nam' => ['VinFast Hà Nam - Phủ Lý'],
        'Hà Tĩnh' => ['VinFast Hà Tĩnh - TP Hà Tĩnh'],
        'Hải Dương' => ['VinFast Hải Dương - Nguyễn Lương Bằng'],
        'Hậu Giang' => ['VinFast Hậu Giang - Vị Thanh'],
        'Khánh Hòa' => ['VinFast Khánh Hòa - Nha Trang'],
        'Kiên Giang' => ['VinFast Kiên Giang - Rạch Giá'],
        'Lâm Đồng' => ['VinFast Lâm Đồng - Đà Lạt'],
        'Long An' => ['VinFast Long An - Tân An'],
        'Nam Định' => ['VinFast Nam Định - Trần Hưng Đạo'],
        'Nghệ An' => ['VinFast Nghệ An - Vinh'],
        'Ninh Bình' => ['VinFast Ninh Bình - Trần Hưng Đạo'],
        'Phú Thọ' => ['VinFast Phú Thọ - Việt Trì'],
        'Quảng Bình' => ['VinFast Quảng Bình - Đồng Hới'],
        'Quảng Nam' => ['VinFast Quảng Nam - Tam Kỳ'],
        'Quảng Ninh' => ['VinFast Quảng Ninh - Hạ Long'],
        'Quảng Trị' => ['VinFast Quảng Trị - Đông Hà'],
        'Sóc Trăng' => ['VinFast Sóc Trăng - Sóc Trăng'],
        'Thanh Hóa' => ['VinFast Thanh Hóa - Thanh Hóa'],
        'Thừa Thiên Huế' => ['VinFast Thừa Thiên Huế - Huế'],
        'Tiền Giang' => ['VinFast Tiền Giang - Mỹ Tho'],
        'Vĩnh Long' => ['VinFast Vĩnh Long - Vĩnh Long'],
        'Vĩnh Phúc' => ['VinFast Vĩnh Phúc - Vĩnh Yên'],
    ],
];
